[theme]
primaryColor = "#209869"
backgroundColor = "#0e1117"
secondaryBackgroundColor = "#262730"
textColor = "#fafafa"
font = "sans serif"

[server]
maxUploadSize = 10

[browser]
gatherUsageStats = false
